
package VISTA;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import MODELO.SqlConection;
public class pageseleccultivo extends javax.swing.JPanel {

    /**
     * Creates new form pageseleccultivo
     */
    public pageseleccultivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1c1 = new javax.swing.JTextField();
        jTextField2c2 = new javax.swing.JTextField();
        jTextField3c3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        Aceptarc = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 238, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SELECCIÓN DE CULTIVO");

        jLabel2.setText("CultivoID");

        jLabel3.setText("Tipo de cultivo");

        jLabel4.setText("Variedad");

        jLabel5.setText("Temporada");

        jTextField1c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1c1ActionPerformed(evt);
            }
        });

        jTextField2c2.setForeground(new java.awt.Color(204, 204, 204));
        jTextField2c2.setText("ejm: papa,  maiz,  quinua,etc.");

        jTextField3c3.setForeground(new java.awt.Color(204, 204, 204));
        jTextField3c3.setText("ejm: maiz amarillo, maiz blanco,etc");

        jTextField4.setForeground(new java.awt.Color(204, 204, 204));
        jTextField4.setText("ejm: invierno, verano, etc");

        Aceptarc.setText("Aceptar");
        Aceptarc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptarcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1c1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2c2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(175, 175, 175)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3c3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 111, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(381, 381, 381))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Aceptarc)
                        .addGap(452, 452, 452))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3c3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Aceptarc)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1c1ActionPerformed

    private void AceptarcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptarcActionPerformed
   String tipo = jTextField2c2.getText().trim();
String variedad = jTextField3c3.getText().trim();
String temporada = jTextField4.getText().trim();

if (tipo.isEmpty()) {
    JOptionPane.showMessageDialog(this, "⚠ El campo 'Tipo de cultivo' es obligatorio.");
    return;
}

try {
    Connection con = MODELO.SqlConection.conectar();
    if (con != null) {
        String sql = "INSERT INTO Cultivo (CulTipo, CulVariedad, CulTemporada) VALUES (?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, tipo);
        ps.setString(2, variedad);
        ps.setString(3, temporada);

        int resultado = ps.executeUpdate();
        if (resultado > 0) {
            JOptionPane.showMessageDialog(this, "✅ ¡Cultivo guardado correctamente!");
            jTextField2c2.setText("");
            jTextField3c3.setText("");
            jTextField4.setText("");
        } else {
            JOptionPane.showMessageDialog(this, "❌ No se pudo guardar el cultivo.");
        }

        con.close();
    } else {
        JOptionPane.showMessageDialog(this, "❌ No se pudo conectar con la base de datos.");
    }

} catch (SQLException e) {
    JOptionPane.showMessageDialog(this, "❌ Error al guardar: " + e.getMessage());
}
    }//GEN-LAST:event_AceptarcActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptarc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1c1;
    private javax.swing.JTextField jTextField2c2;
    private javax.swing.JTextField jTextField3c3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
