/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import java.awt.BorderLayout;

/**
 *
 * @author ACER
 */
public class page3 extends javax.swing.JPanel {

    /**
     * Creates new form page1
     */
    public page3() {
        initComponents();
        page03cultivo p03c = new page03cultivo();
        p03c.setSize(1272,372);
        p03c.setLocation(0, 0);
        
        contCulPro.removeAll();
        contCulPro.add(p03c,BorderLayout.CENTER);
        contCulPro.revalidate();
        contCulPro.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sg = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        contCulPro = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(1268, 478));
        setPreferredSize(new java.awt.Dimension(1268, 478));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sg.setPreferredSize(new java.awt.Dimension(1266, 484));

        jButton1.setText("CULTIVO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("PRODUCCIÓN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contCulProLayout = new javax.swing.GroupLayout(contCulPro);
        contCulPro.setLayout(contCulProLayout);
        contCulProLayout.setHorizontalGroup(
            contCulProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contCulProLayout.setVerticalGroup(
            contCulProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 372, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sgLayout = new javax.swing.GroupLayout(sg);
        sg.setLayout(sgLayout);
        sgLayout.setHorizontalGroup(
            sgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgLayout.createSequentialGroup()
                .addGroup(sgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sgLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contCulPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, sgLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 2, Short.MAX_VALUE))
        );
        sgLayout.setVerticalGroup(
            sgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sgLayout.createSequentialGroup()
                .addGroup(sgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contCulPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(sg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 420));

        getAccessibleContext().setAccessibleName("");
        getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        page03cultivo p03c = new page03cultivo();
        p03c.setSize(1272,372);
        p03c.setLocation(0, 0);
        
        contCulPro.removeAll();
        contCulPro.add(p03c,BorderLayout.CENTER);
        contCulPro.revalidate();
        contCulPro.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         page03produccion p03p = new page03produccion();
        p03p.setSize(1272,372);
        p03p.setLocation(0, 0);
        
        contCulPro.removeAll();
        contCulPro.add(p03p,BorderLayout.CENTER);
        contCulPro.revalidate();
        contCulPro.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contCulPro;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel sg;
    // End of variables declaration//GEN-END:variables
}
