/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

import java.awt.BorderLayout;

/**
 *
 * @author ACER
 */
public class pageregistrar extends javax.swing.JPanel {

    /**
     * Creates new form pagecultivo
     */
    public pageregistrar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnInfTerreno = new javax.swing.JButton();
        BtnInfTerreno1 = new javax.swing.JButton();
        BtnInfTerreno2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cont3pasos = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 255, 204));

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        BtnInfTerreno.setText("INFORMACIÓN DEL TERRENO");
        BtnInfTerreno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfTerrenoActionPerformed(evt);
            }
        });

        BtnInfTerreno1.setText("SELECCIÓN DE CULTIVO");
        BtnInfTerreno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfTerreno1ActionPerformed(evt);
            }
        });

        BtnInfTerreno2.setText("DETALLE DEL CICLO DE CULTIVO");
        BtnInfTerreno2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnInfTerreno2ActionPerformed(evt);
            }
        });

        jButton1.setText("salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("retroceder");

        jButton3.setText("continuar");

        cont3pasos.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout cont3pasosLayout = new javax.swing.GroupLayout(cont3pasos);
        cont3pasos.setLayout(cont3pasosLayout);
        cont3pasosLayout.setHorizontalGroup(
            cont3pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        cont3pasosLayout.setVerticalGroup(
            cont3pasosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(38, 38, 38))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cont3pasos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtnInfTerreno, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnInfTerreno1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnInfTerreno2, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnInfTerreno2)
                    .addComponent(BtnInfTerreno1)
                    .addComponent(BtnInfTerreno))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cont3pasos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnInfTerrenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfTerrenoActionPerformed
        pageinfoterreno pt = new pageinfoterreno();
        pt.setSize(1005,308);
        pt.setLocation(0, 0);
        
        cont3pasos.removeAll();
        cont3pasos.add(pt,BorderLayout.CENTER);
        cont3pasos.revalidate();
        cont3pasos.repaint();
    }//GEN-LAST:event_BtnInfTerrenoActionPerformed

    private void BtnInfTerreno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfTerreno1ActionPerformed
        pageseleccultivo pc = new pageseleccultivo();
        pc.setSize(1005,308);
        pc.setLocation(0, 0);
        
        cont3pasos.removeAll();
        cont3pasos.add(pc,BorderLayout.CENTER);
        cont3pasos.revalidate();
        cont3pasos.repaint();
    }//GEN-LAST:event_BtnInfTerreno1ActionPerformed

    private void BtnInfTerreno2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnInfTerreno2ActionPerformed
        pagedetallecultivo pdc = new pagedetallecultivo();
        pdc.setSize(1005,308);
        pdc.setLocation(0, 0);
        
        cont3pasos.removeAll();
        cont3pasos.add(pdc,BorderLayout.CENTER);
        cont3pasos.revalidate();
        cont3pasos.repaint();
    }//GEN-LAST:event_BtnInfTerreno2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnInfTerreno;
    private javax.swing.JButton BtnInfTerreno1;
    private javax.swing.JButton BtnInfTerreno2;
    private javax.swing.JPanel cont3pasos;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
