
package VISTA;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import MODELO.SqlConection;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
public class pagedetallecultivo extends javax.swing.JPanel {

    /**
     * Creates new form pagedetallecultivo
     */
    public pagedetallecultivo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1d1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2d2 = new javax.swing.JTextField();
        jTextField3d3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        Aceptard = new javax.swing.JButton();

        setBackground(new java.awt.Color(242, 238, 232));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("DETALLE DEL CICLO DE CULTIVO");

        jLabel2.setText("Responsable del cultivo");

        jLabel3.setText("Fecha de cosecha");

        jLabel4.setText("Fecha de siembra");

        jLabel5.setText("Observaciones");

        Aceptard.setText("Aceptar");
        Aceptard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AceptardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(381, 381, 381))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Aceptard)
                        .addGap(452, 452, 452))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1d1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2d2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3d3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 64, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1d1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2d2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3d3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(Aceptard)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void AceptardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AceptardActionPerformed
      String responsable = jTextField1d1.getText().trim();
    String fechaCosechaStr = jTextField2d2.getText().trim();
    String fechaSiembraStr = jTextField3d3.getText().trim();
    String observaciones = jTextField4.getText().trim();

    if (responsable.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠ El campo 'Responsable del cultivo' es obligatorio.");
        return;
    }
    if (fechaSiembraStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "⚠ El campo 'Fecha de siembra' es obligatorio.");
        return;
    }

    // Convertir las fechas String a java.sql.Date
    SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
    Date fechaSiembra = null;
    Date fechaCosecha = null;

    try {
        java.util.Date fechaSiembraUtil = formato.parse(fechaSiembraStr);
        fechaSiembra = new Date(fechaSiembraUtil.getTime());

        if (!fechaCosechaStr.isEmpty()) {
            java.util.Date fechaCosechaUtil = formato.parse(fechaCosechaStr);
            fechaCosecha = new Date(fechaCosechaUtil.getTime());
        }
    } catch (ParseException e) {
        JOptionPane.showMessageDialog(this, "⚠ El formato de fecha debe ser yyyy-MM-dd (ej: 2025-05-29).");
        return;
    }

    // IDCultivo fijo para ejemplo (modifica según tu lógica)
    int idCultivo = 1; 

    try {
        Connection con = SqlConection.conectar();
        if (con != null) {
            String sql = "INSERT INTO DetalleCultivo (IDCultivo, DtcResponsable, DtcFechaSiembra, DtcFechaCosecha, DtcObservaciones) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idCultivo);
            ps.setString(2, responsable);
            ps.setDate(3, fechaSiembra);
            if (fechaCosecha != null) {
                ps.setDate(4, fechaCosecha);
            } else {
                ps.setNull(4, java.sql.Types.DATE);
            }
            ps.setString(5, observaciones.isEmpty() ? null : observaciones);

            int resultado = ps.executeUpdate();
            if (resultado > 0) {
                JOptionPane.showMessageDialog(this, "✅ ¡Detalle del cultivo guardado correctamente!");
                // Limpiar campos
                jTextField1d1.setText("");
                jTextField2d2.setText("");
                jTextField3d3.setText("");
                jTextField4.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "❌ No se pudo guardar el detalle del cultivo.");
            }
            con.close();
        } else {
            JOptionPane.showMessageDialog(this, "❌ No se pudo conectar con la base de datos.");
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "❌ Error al guardar: " + e.getMessage());
    }
    }//GEN-LAST:event_AceptardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptard;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1d1;
    private javax.swing.JTextField jTextField2d2;
    private javax.swing.JTextField jTextField3d3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
