/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import java.awt.BorderLayout;

/**
 *
 * @author ACER
 */
public class PRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        page01 p1 = new page01();
        p1.setSize(1266,484);
        p1.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p1,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        page03 = new javax.swing.JButton();
        page4 = new javax.swing.JButton();
        page5 = new javax.swing.JButton();
        page6 = new javax.swing.JButton();
        page7 = new javax.swing.JButton();
        page8 = new javax.swing.JButton();
        contenidoPage3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(232, 245, 233));

        page03.setBackground(new java.awt.Color(200, 230, 201));
        page03.setText("GESTIÓN DE CULTIVOS Y PRODUCCIÓN");
        page03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page03ActionPerformed(evt);
            }
        });

        page4.setBackground(new java.awt.Color(200, 230, 201));
        page4.setForeground(new java.awt.Color(46, 125, 50));
        page4.setText("GESTION DE USUARIO");
        page4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page4ActionPerformed(evt);
            }
        });

        page5.setBackground(new java.awt.Color(200, 230, 201));
        page5.setText("MONITOREO Y PREDICCIÓN AGRICOLA");
        page5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page5ActionPerformed(evt);
            }
        });

        page6.setBackground(new java.awt.Color(200, 230, 201));
        page6.setText("CAPACITACIÓN Y ASESORIA TECNICA");
        page6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page6ActionPerformed(evt);
            }
        });

        page7.setBackground(new java.awt.Color(200, 230, 201));
        page7.setText("COMERCIO LOGISTICA Y RESULTADOS");
        page7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page7ActionPerformed(evt);
            }
        });

        page8.setBackground(new java.awt.Color(200, 230, 201));
        page8.setText("DASHBOARD");
        page8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                page8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contenidoPage3Layout = new javax.swing.GroupLayout(contenidoPage3);
        contenidoPage3.setLayout(contenidoPage3Layout);
        contenidoPage3Layout.setHorizontalGroup(
            contenidoPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        contenidoPage3Layout.setVerticalGroup(
            contenidoPage3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(page4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page03)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page7, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(page8, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(contenidoPage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(page03, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(page4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(page6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(page7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(page5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(page8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenidoPage3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void page03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page03ActionPerformed
         page3 p3 = new page3();
        p3.setSize(1266,484);
        p3.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p3,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();
    }//GEN-LAST:event_page03ActionPerformed

    private void page4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page4ActionPerformed
        page01 p1 = new page01();
        p1.setSize(1266,484);
        p1.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p1,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();
    }//GEN-LAST:event_page4ActionPerformed

    private void page5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page5ActionPerformed
        page02 p2 = new page02();
        p2.setSize(1266,484);
        p2.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p2,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();
    }//GEN-LAST:event_page5ActionPerformed

    private void page6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page6ActionPerformed
     page04 p4 = new page04();
        p4.setSize(1266,484);
        p4.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p4,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();   
    }//GEN-LAST:event_page6ActionPerformed

    private void page7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page7ActionPerformed
        page05 p5 = new page05();
        p5.setSize(1266,484);
        p5.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p5,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();  
    }//GEN-LAST:event_page7ActionPerformed

    private void page8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_page8ActionPerformed
        page06 p6 = new page06();
        p6.setSize(1266,484);
        p6.setLocation(0, 0);
        
        contenidoPage3.removeAll();
        contenidoPage3.add(p6,BorderLayout.CENTER);
        contenidoPage3.revalidate();
        contenidoPage3.repaint();  
    }//GEN-LAST:event_page8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenidoPage3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton page03;
    private javax.swing.JButton page4;
    private javax.swing.JButton page5;
    private javax.swing.JButton page6;
    private javax.swing.JButton page7;
    private javax.swing.JButton page8;
    // End of variables declaration//GEN-END:variables
}
